#!/bin/bash
alias dcom='docker compose'
alias ll='ls -l'
alias pyunit='python -m unittest'
alias gull='git pull'
alias gush='git push'
alias gst='git stash'
alias gc='git checkout'
alias gb='git branch'
alias grb='git rebase'
alias greset='git reset'
alias gs='git status'
alias ga='git add'
alias gr='git rm'
alias gcm='git commit -m'
alias glog='git log'
